//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNLV_CORPORATION
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cheque_Good
    {
        public int ID_ChequeGood { get; set; }
        public decimal SumOfCheque { get; set; }
        public int Good_ID { get; set; }
        public int Cheque_ID { get; set; }
    
        public virtual Cheque Cheque {private get; set; }
        public virtual Goods Goods {private get; set; }
    }
}
