//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNLV_CORPORATION
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cheque
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cheque()
        {
            this.Cheque_Good = new HashSet<Cheque_Good>();
        }
    
        public int ID_Cheque { get; set; }
        public int NumberCheque { get; set; }
        public int Client_ID { get; set; }
        public int Employee_ID { get; set; }
    
        public virtual Clients Clients {private get; set; }
        public virtual Employees Employees {private get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cheque_Good> Cheque_Good {private get; set; }
    }
}
