//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNLV_CORPORATION
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clients()
        {
            this.Cheque = new HashSet<Cheque>();
            this.Client_History = new HashSet<Client_History>();
        }
    
        public int ID_Client { get; set; }
        public string FirstNameClient { get; set; }
        public string SurNameClient { get; set; }
        public string MiddleNameClient { get; set; }
        public string PhoneNumberClient { get; set; }
        public int StatusClient_ID { get; set; }
        public int Role_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cheque> Cheque {private get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client_History> Client_History {private get; set; }
        public virtual Roles Roles {private get; set; }
        public virtual ClientStatus ClientStatus {private get; set; }
    }
}
