//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNLV_CORPORATION
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_History
    {
        public int ID_ClientHistory { get; set; }
        public int Client_ID { get; set; }
        public int ViewHistory_ID { get; set; }
    
        public virtual Clients Clients {private get; set; }
        public virtual View_History View_History {private get; set; }
    }
}
