//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNLV_CORPORATION
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employees()
        {
            this.Cheque = new HashSet<Cheque>();
        }
    
        public int ID_Employee { get; set; }
        public string FirstNameEmployee { get; set; }
        public string SurNameEmployee { get; set; }
        public string MiddleNameEmployee { get; set; }
        public int Post_ID { get; set; }
        public int Role_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cheque> Cheque {private get; set; }
        public virtual PostEmployee PostEmployee {private get; set; }
        public virtual Roles Roles {private get; set; }
    }
}
