//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNLV_CORPORATION
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UNLV_CORPORATIONEntities1 : DbContext
    {
        public UNLV_CORPORATIONEntities1()
            : base("name=UNLV_CORPORATIONEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Avt> Avt { get; set; }
        public virtual DbSet<Cheque> Cheque { get; set; }
        public virtual DbSet<Cheque_Good> Cheque_Good { get; set; }
        public virtual DbSet<Client_History> Client_History { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<ClientStatus> ClientStatus { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Good_Article> Good_Article { get; set; }
        public virtual DbSet<Goods> Goods { get; set; }
        public virtual DbSet<PostEmployee> PostEmployee { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Stocks> Stocks { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<View_History> View_History { get; set; }
    }
}
